// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ui_sidebar_mode.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.Enums.UiSidebarMode {

  /// <summary>Holder for reflection information generated from ui_sidebar_mode.proto</summary>
  public static partial class UiSidebarModeReflection {

    #region Descriptor
    /// <summary>File descriptor for ui_sidebar_mode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UiSidebarModeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChV1aV9zaWRlYmFyX21vZGUucHJvdG8SG3Byb3RvLmVudW1zLnVpX3NpZGVi",
            "YXJfbW9kZSqgCQoPdWlfc2lkZWJhcl9tb2RlEgsKB0RlZmF1bHQQABIKCgZT",
            "cXVhZHMQARIRCg1EZXNpZ25hdGVNaW5lEAISGAoURGVzaWduYXRlUmVtb3Zl",
            "UmFtcHMQAxIUChBEZXNpZ25hdGVVcFN0YWlyEAQSFgoSRGVzaWduYXRlRG93",
            "blN0YWlyEAUSGAoURGVzaWduYXRlVXBEb3duU3RhaXIQBhITCg9EZXNpZ25h",
            "dGVVcFJhbXAQBxIUChBEZXNpZ25hdGVDaGFubmVsEAgSGQoVRGVzaWduYXRl",
            "R2F0aGVyUGxhbnRzEAkSHgoaRGVzaWduYXRlUmVtb3ZlRGVzaWduYXRpb24Q",
            "ChITCg9EZXNpZ25hdGVTbW9vdGgQCxIXChNEZXNpZ25hdGVDYXJ2ZVRyYWNr",
            "EAwSFAoQRGVzaWduYXRlRW5ncmF2ZRANEh8KG0Rlc2lnbmF0ZUNhcnZlRm9y",
            "dGlmaWNhdGlvbhAOEg4KClN0b2NrcGlsZXMQDxIJCgVCdWlsZBAQEhEKDVF1",
            "ZXJ5QnVpbGRpbmcQERIKCgZPcmRlcnMQEhIQCgxPcmRlcnNGb3JiaWQQExIQ",
            "CgxPcmRlcnNSZWZ1c2UQFBISCg5PcmRlcnNXb3Jrc2hvcBAVEg4KCk9yZGVy",
            "c1pvbmUQFhIRCg1CdWlsZGluZ0l0ZW1zEBcSDQoJVmlld1VuaXRzEBgSDgoK",
            "TG9va0Fyb3VuZBAZEhcKE0Rlc2lnbmF0ZUl0ZW1zQ2xhaW0QGhIYChREZXNp",
            "Z25hdGVJdGVtc0ZvcmJpZBAbEhYKEkRlc2lnbmF0ZUl0ZW1zTWVsdBAcEhgK",
            "FERlc2lnbmF0ZUl0ZW1zVW5tZWx0EB0SFgoSRGVzaWduYXRlSXRlbXNEdW1w",
            "EB4SGAoURGVzaWduYXRlSXRlbXNVbmR1bXAQHxIWChJEZXNpZ25hdGVJdGVt",
            "c0hpZGUQIBIYChREZXNpZ25hdGVJdGVtc1VuaGlkZRAhEhYKEkRlc2lnbmF0",
            "ZUNob3BUcmVlcxAiEh0KGURlc2lnbmF0ZVRvZ2dsZUVuZ3JhdmluZ3MQIxIZ",
            "ChVEZXNpZ25hdGVUb2dnbGVNYXJrZXIQJBILCgdIb3RrZXlzECUSGAoURGVz",
            "aWduYXRlVHJhZmZpY0hpZ2gQJhIaChZEZXNpZ25hdGVUcmFmZmljTm9ybWFs",
            "ECcSFwoTRGVzaWduYXRlVHJhZmZpY0xvdxAoEh4KGkRlc2lnbmF0ZVRyYWZm",
            "aWNSZXN0cmljdGVkECkSCQoFWm9uZXMQKhIQCgxab25lc1BlbkluZm8QKxIQ",
            "Cgxab25lc1BpdEluZm8QLBIVChFab25lc0hvc3BpdGFsSW5mbxAtEhMKD1pv",
            "bmVzR2F0aGVySW5mbxAuEh8KG0Rlc2lnbmF0ZVJlbW92ZUNvbnN0cnVjdGlv",
            "bhAvEg8KC0RlcG90QWNjZXNzEDASDwoLTm90ZXNQb2ludHMQMRIPCgtOb3Rl",
            "c1JvdXRlcxAyEgsKB0J1cnJvd3MQMxILCgdIYXVsaW5nEDQSEAoMQXJlbmFX",
            "ZWF0aGVyEDUSDgoKQXJlbmFUcmVlcxA2QgJIAw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.Enums.UiSidebarMode.ui_sidebar_mode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ui_sidebar_mode {
    [pbr::OriginalName("Default")] Default = 0,
    [pbr::OriginalName("Squads")] Squads = 1,
    [pbr::OriginalName("DesignateMine")] DesignateMine = 2,
    [pbr::OriginalName("DesignateRemoveRamps")] DesignateRemoveRamps = 3,
    [pbr::OriginalName("DesignateUpStair")] DesignateUpStair = 4,
    [pbr::OriginalName("DesignateDownStair")] DesignateDownStair = 5,
    [pbr::OriginalName("DesignateUpDownStair")] DesignateUpDownStair = 6,
    [pbr::OriginalName("DesignateUpRamp")] DesignateUpRamp = 7,
    [pbr::OriginalName("DesignateChannel")] DesignateChannel = 8,
    [pbr::OriginalName("DesignateGatherPlants")] DesignateGatherPlants = 9,
    [pbr::OriginalName("DesignateRemoveDesignation")] DesignateRemoveDesignation = 10,
    [pbr::OriginalName("DesignateSmooth")] DesignateSmooth = 11,
    [pbr::OriginalName("DesignateCarveTrack")] DesignateCarveTrack = 12,
    [pbr::OriginalName("DesignateEngrave")] DesignateEngrave = 13,
    [pbr::OriginalName("DesignateCarveFortification")] DesignateCarveFortification = 14,
    [pbr::OriginalName("Stockpiles")] Stockpiles = 15,
    [pbr::OriginalName("Build")] Build = 16,
    [pbr::OriginalName("QueryBuilding")] QueryBuilding = 17,
    [pbr::OriginalName("Orders")] Orders = 18,
    [pbr::OriginalName("OrdersForbid")] OrdersForbid = 19,
    [pbr::OriginalName("OrdersRefuse")] OrdersRefuse = 20,
    [pbr::OriginalName("OrdersWorkshop")] OrdersWorkshop = 21,
    [pbr::OriginalName("OrdersZone")] OrdersZone = 22,
    [pbr::OriginalName("BuildingItems")] BuildingItems = 23,
    [pbr::OriginalName("ViewUnits")] ViewUnits = 24,
    [pbr::OriginalName("LookAround")] LookAround = 25,
    [pbr::OriginalName("DesignateItemsClaim")] DesignateItemsClaim = 26,
    [pbr::OriginalName("DesignateItemsForbid")] DesignateItemsForbid = 27,
    [pbr::OriginalName("DesignateItemsMelt")] DesignateItemsMelt = 28,
    [pbr::OriginalName("DesignateItemsUnmelt")] DesignateItemsUnmelt = 29,
    [pbr::OriginalName("DesignateItemsDump")] DesignateItemsDump = 30,
    [pbr::OriginalName("DesignateItemsUndump")] DesignateItemsUndump = 31,
    [pbr::OriginalName("DesignateItemsHide")] DesignateItemsHide = 32,
    [pbr::OriginalName("DesignateItemsUnhide")] DesignateItemsUnhide = 33,
    [pbr::OriginalName("DesignateChopTrees")] DesignateChopTrees = 34,
    [pbr::OriginalName("DesignateToggleEngravings")] DesignateToggleEngravings = 35,
    [pbr::OriginalName("DesignateToggleMarker")] DesignateToggleMarker = 36,
    [pbr::OriginalName("Hotkeys")] Hotkeys = 37,
    [pbr::OriginalName("DesignateTrafficHigh")] DesignateTrafficHigh = 38,
    [pbr::OriginalName("DesignateTrafficNormal")] DesignateTrafficNormal = 39,
    [pbr::OriginalName("DesignateTrafficLow")] DesignateTrafficLow = 40,
    [pbr::OriginalName("DesignateTrafficRestricted")] DesignateTrafficRestricted = 41,
    [pbr::OriginalName("Zones")] Zones = 42,
    [pbr::OriginalName("ZonesPenInfo")] ZonesPenInfo = 43,
    [pbr::OriginalName("ZonesPitInfo")] ZonesPitInfo = 44,
    [pbr::OriginalName("ZonesHospitalInfo")] ZonesHospitalInfo = 45,
    [pbr::OriginalName("ZonesGatherInfo")] ZonesGatherInfo = 46,
    [pbr::OriginalName("DesignateRemoveConstruction")] DesignateRemoveConstruction = 47,
    [pbr::OriginalName("DepotAccess")] DepotAccess = 48,
    [pbr::OriginalName("NotesPoints")] NotesPoints = 49,
    [pbr::OriginalName("NotesRoutes")] NotesRoutes = 50,
    [pbr::OriginalName("Burrows")] Burrows = 51,
    [pbr::OriginalName("Hauling")] Hauling = 52,
    [pbr::OriginalName("ArenaWeather")] ArenaWeather = 53,
    [pbr::OriginalName("ArenaTrees")] ArenaTrees = 54,
  }

  #endregion

}

#endregion Designer generated code
