// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BasicApi.proto
// </auto-generated>
// Original file comments:
// ==== THIS FILE IS AUTO-GENERATED. DO NOT EDIT. ===
// This file is a slightly improved version of the same .proto file located in /proto. It is autogenerated.
// The only differences are: 1) Added some missing imports. 2) Added 'service' block (based on '// RPC' comments, if any).
// ==================================================
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dfproto {
  public static partial class BasicApiRpcService
  {
    static readonly string __ServiceName = "dfproto.BasicApiRpcService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.EmptyMessage> __Marshaller_dfproto_EmptyMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.EmptyMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.StringMessage> __Marshaller_dfproto_StringMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.StringMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.GetWorldInfoOut> __Marshaller_dfproto_GetWorldInfoOut = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.GetWorldInfoOut.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.ListEnumsOut> __Marshaller_dfproto_ListEnumsOut = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.ListEnumsOut.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.ListJobSkillsOut> __Marshaller_dfproto_ListJobSkillsOut = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.ListJobSkillsOut.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.ListMaterialsIn> __Marshaller_dfproto_ListMaterialsIn = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.ListMaterialsIn.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.ListMaterialsOut> __Marshaller_dfproto_ListMaterialsOut = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.ListMaterialsOut.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.ListUnitsIn> __Marshaller_dfproto_ListUnitsIn = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.ListUnitsIn.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.ListUnitsOut> __Marshaller_dfproto_ListUnitsOut = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.ListUnitsOut.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.ListSquadsIn> __Marshaller_dfproto_ListSquadsIn = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.ListSquadsIn.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.ListSquadsOut> __Marshaller_dfproto_ListSquadsOut = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.ListSquadsOut.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.SetUnitLaborsIn> __Marshaller_dfproto_SetUnitLaborsIn = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.SetUnitLaborsIn.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.StringMessage> __Method_GetVersion = new grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.StringMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetVersion",
        __Marshaller_dfproto_EmptyMessage,
        __Marshaller_dfproto_StringMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.StringMessage> __Method_GetDFVersion = new grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.StringMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDFVersion",
        __Marshaller_dfproto_EmptyMessage,
        __Marshaller_dfproto_StringMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.GetWorldInfoOut> __Method_GetWorldInfo = new grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.GetWorldInfoOut>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetWorldInfo",
        __Marshaller_dfproto_EmptyMessage,
        __Marshaller_dfproto_GetWorldInfoOut);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.ListEnumsOut> __Method_ListEnums = new grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.ListEnumsOut>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListEnums",
        __Marshaller_dfproto_EmptyMessage,
        __Marshaller_dfproto_ListEnumsOut);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.ListJobSkillsOut> __Method_ListJobSkills = new grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.ListJobSkillsOut>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListJobSkills",
        __Marshaller_dfproto_EmptyMessage,
        __Marshaller_dfproto_ListJobSkillsOut);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.ListMaterialsIn, global::Dfproto.ListMaterialsOut> __Method_ListMaterials = new grpc::Method<global::Dfproto.ListMaterialsIn, global::Dfproto.ListMaterialsOut>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListMaterials",
        __Marshaller_dfproto_ListMaterialsIn,
        __Marshaller_dfproto_ListMaterialsOut);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.ListUnitsIn, global::Dfproto.ListUnitsOut> __Method_ListUnits = new grpc::Method<global::Dfproto.ListUnitsIn, global::Dfproto.ListUnitsOut>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListUnits",
        __Marshaller_dfproto_ListUnitsIn,
        __Marshaller_dfproto_ListUnitsOut);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.ListSquadsIn, global::Dfproto.ListSquadsOut> __Method_ListSquads = new grpc::Method<global::Dfproto.ListSquadsIn, global::Dfproto.ListSquadsOut>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListSquads",
        __Marshaller_dfproto_ListSquadsIn,
        __Marshaller_dfproto_ListSquadsOut);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.SetUnitLaborsIn, global::Dfproto.EmptyMessage> __Method_SetUnitLabors = new grpc::Method<global::Dfproto.SetUnitLaborsIn, global::Dfproto.EmptyMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetUnitLabors",
        __Marshaller_dfproto_SetUnitLaborsIn,
        __Marshaller_dfproto_EmptyMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dfproto.BasicApiReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of BasicApiRpcService</summary>
    [grpc::BindServiceMethod(typeof(BasicApiRpcService), "BindService")]
    public abstract partial class BasicApiRpcServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.StringMessage> GetVersion(global::Dfproto.EmptyMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.StringMessage> GetDFVersion(global::Dfproto.EmptyMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.GetWorldInfoOut> GetWorldInfo(global::Dfproto.EmptyMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.ListEnumsOut> ListEnums(global::Dfproto.EmptyMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.ListJobSkillsOut> ListJobSkills(global::Dfproto.EmptyMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.ListMaterialsOut> ListMaterials(global::Dfproto.ListMaterialsIn request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.ListUnitsOut> ListUnits(global::Dfproto.ListUnitsIn request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.ListSquadsOut> ListSquads(global::Dfproto.ListSquadsIn request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.EmptyMessage> SetUnitLabors(global::Dfproto.SetUnitLaborsIn request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for BasicApiRpcService</summary>
    public partial class BasicApiRpcServiceClient : grpc::ClientBase<BasicApiRpcServiceClient>
    {
      /// <summary>Creates a new client for BasicApiRpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public BasicApiRpcServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BasicApiRpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public BasicApiRpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected BasicApiRpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected BasicApiRpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.StringMessage GetVersion(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVersion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.StringMessage GetVersion(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVersion, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.StringMessage> GetVersionAsync(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVersionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.StringMessage> GetVersionAsync(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVersion, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.StringMessage GetDFVersion(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDFVersion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.StringMessage GetDFVersion(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDFVersion, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.StringMessage> GetDFVersionAsync(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDFVersionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.StringMessage> GetDFVersionAsync(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDFVersion, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.GetWorldInfoOut GetWorldInfo(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWorldInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.GetWorldInfoOut GetWorldInfo(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWorldInfo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.GetWorldInfoOut> GetWorldInfoAsync(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWorldInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.GetWorldInfoOut> GetWorldInfoAsync(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWorldInfo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.ListEnumsOut ListEnums(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListEnums(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.ListEnumsOut ListEnums(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListEnums, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.ListEnumsOut> ListEnumsAsync(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListEnumsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.ListEnumsOut> ListEnumsAsync(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListEnums, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.ListJobSkillsOut ListJobSkills(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListJobSkills(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.ListJobSkillsOut ListJobSkills(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListJobSkills, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.ListJobSkillsOut> ListJobSkillsAsync(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListJobSkillsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.ListJobSkillsOut> ListJobSkillsAsync(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListJobSkills, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.ListMaterialsOut ListMaterials(global::Dfproto.ListMaterialsIn request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListMaterials(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.ListMaterialsOut ListMaterials(global::Dfproto.ListMaterialsIn request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListMaterials, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.ListMaterialsOut> ListMaterialsAsync(global::Dfproto.ListMaterialsIn request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListMaterialsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.ListMaterialsOut> ListMaterialsAsync(global::Dfproto.ListMaterialsIn request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListMaterials, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.ListUnitsOut ListUnits(global::Dfproto.ListUnitsIn request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListUnits(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.ListUnitsOut ListUnits(global::Dfproto.ListUnitsIn request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListUnits, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.ListUnitsOut> ListUnitsAsync(global::Dfproto.ListUnitsIn request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListUnitsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.ListUnitsOut> ListUnitsAsync(global::Dfproto.ListUnitsIn request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListUnits, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.ListSquadsOut ListSquads(global::Dfproto.ListSquadsIn request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListSquads(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.ListSquadsOut ListSquads(global::Dfproto.ListSquadsIn request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListSquads, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.ListSquadsOut> ListSquadsAsync(global::Dfproto.ListSquadsIn request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListSquadsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.ListSquadsOut> ListSquadsAsync(global::Dfproto.ListSquadsIn request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListSquads, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.EmptyMessage SetUnitLabors(global::Dfproto.SetUnitLaborsIn request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetUnitLabors(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.EmptyMessage SetUnitLabors(global::Dfproto.SetUnitLaborsIn request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetUnitLabors, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.EmptyMessage> SetUnitLaborsAsync(global::Dfproto.SetUnitLaborsIn request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetUnitLaborsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.EmptyMessage> SetUnitLaborsAsync(global::Dfproto.SetUnitLaborsIn request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetUnitLabors, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override BasicApiRpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BasicApiRpcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(BasicApiRpcServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetVersion, serviceImpl.GetVersion)
          .AddMethod(__Method_GetDFVersion, serviceImpl.GetDFVersion)
          .AddMethod(__Method_GetWorldInfo, serviceImpl.GetWorldInfo)
          .AddMethod(__Method_ListEnums, serviceImpl.ListEnums)
          .AddMethod(__Method_ListJobSkills, serviceImpl.ListJobSkills)
          .AddMethod(__Method_ListMaterials, serviceImpl.ListMaterials)
          .AddMethod(__Method_ListUnits, serviceImpl.ListUnits)
          .AddMethod(__Method_ListSquads, serviceImpl.ListSquads)
          .AddMethod(__Method_SetUnitLabors, serviceImpl.SetUnitLabors).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, BasicApiRpcServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetVersion, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.EmptyMessage, global::Dfproto.StringMessage>(serviceImpl.GetVersion));
      serviceBinder.AddMethod(__Method_GetDFVersion, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.EmptyMessage, global::Dfproto.StringMessage>(serviceImpl.GetDFVersion));
      serviceBinder.AddMethod(__Method_GetWorldInfo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.EmptyMessage, global::Dfproto.GetWorldInfoOut>(serviceImpl.GetWorldInfo));
      serviceBinder.AddMethod(__Method_ListEnums, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.EmptyMessage, global::Dfproto.ListEnumsOut>(serviceImpl.ListEnums));
      serviceBinder.AddMethod(__Method_ListJobSkills, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.EmptyMessage, global::Dfproto.ListJobSkillsOut>(serviceImpl.ListJobSkills));
      serviceBinder.AddMethod(__Method_ListMaterials, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.ListMaterialsIn, global::Dfproto.ListMaterialsOut>(serviceImpl.ListMaterials));
      serviceBinder.AddMethod(__Method_ListUnits, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.ListUnitsIn, global::Dfproto.ListUnitsOut>(serviceImpl.ListUnits));
      serviceBinder.AddMethod(__Method_ListSquads, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.ListSquadsIn, global::Dfproto.ListSquadsOut>(serviceImpl.ListSquads));
      serviceBinder.AddMethod(__Method_SetUnitLabors, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.SetUnitLaborsIn, global::Dfproto.EmptyMessage>(serviceImpl.SetUnitLabors));
    }

  }
}
#endregion
