// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CoreProtocol.proto
// </auto-generated>
// Original file comments:
// ==== THIS FILE IS AUTO-GENERATED. DO NOT EDIT. ===
// This file is a slightly improved version of the same .proto file located in /proto. It is autogenerated.
// The only differences are: 1) Added some missing imports. 2) Added 'service' block (based on '// RPC' comments, if any).
// ==================================================
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dfproto {
  public static partial class CoreProtocolRpcService
  {
    static readonly string __ServiceName = "dfproto.CoreProtocolRpcService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.CoreBindRequest> __Marshaller_dfproto_CoreBindRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.CoreBindRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.CoreBindReply> __Marshaller_dfproto_CoreBindReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.CoreBindReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.CoreRunCommandRequest> __Marshaller_dfproto_CoreRunCommandRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.CoreRunCommandRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.EmptyMessage> __Marshaller_dfproto_EmptyMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.EmptyMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.IntMessage> __Marshaller_dfproto_IntMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.IntMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.CoreRunLuaRequest> __Marshaller_dfproto_CoreRunLuaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.CoreRunLuaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dfproto.StringListMessage> __Marshaller_dfproto_StringListMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dfproto.StringListMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.CoreBindRequest, global::Dfproto.CoreBindReply> __Method_BindMethod = new grpc::Method<global::Dfproto.CoreBindRequest, global::Dfproto.CoreBindReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BindMethod",
        __Marshaller_dfproto_CoreBindRequest,
        __Marshaller_dfproto_CoreBindReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.CoreRunCommandRequest, global::Dfproto.EmptyMessage> __Method_RunCommand = new grpc::Method<global::Dfproto.CoreRunCommandRequest, global::Dfproto.EmptyMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RunCommand",
        __Marshaller_dfproto_CoreRunCommandRequest,
        __Marshaller_dfproto_EmptyMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.IntMessage> __Method_CoreSuspend = new grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.IntMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CoreSuspend",
        __Marshaller_dfproto_EmptyMessage,
        __Marshaller_dfproto_IntMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.IntMessage> __Method_CoreResume = new grpc::Method<global::Dfproto.EmptyMessage, global::Dfproto.IntMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CoreResume",
        __Marshaller_dfproto_EmptyMessage,
        __Marshaller_dfproto_IntMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dfproto.CoreRunLuaRequest, global::Dfproto.StringListMessage> __Method_RunLua = new grpc::Method<global::Dfproto.CoreRunLuaRequest, global::Dfproto.StringListMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RunLua",
        __Marshaller_dfproto_CoreRunLuaRequest,
        __Marshaller_dfproto_StringListMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dfproto.CoreProtocolReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CoreProtocolRpcService</summary>
    [grpc::BindServiceMethod(typeof(CoreProtocolRpcService), "BindService")]
    public abstract partial class CoreProtocolRpcServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.CoreBindReply> BindMethod(global::Dfproto.CoreBindRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.EmptyMessage> RunCommand(global::Dfproto.CoreRunCommandRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.IntMessage> CoreSuspend(global::Dfproto.EmptyMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.IntMessage> CoreResume(global::Dfproto.EmptyMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Dfproto.StringListMessage> RunLua(global::Dfproto.CoreRunLuaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CoreProtocolRpcService</summary>
    public partial class CoreProtocolRpcServiceClient : grpc::ClientBase<CoreProtocolRpcServiceClient>
    {
      /// <summary>Creates a new client for CoreProtocolRpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public CoreProtocolRpcServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CoreProtocolRpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public CoreProtocolRpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected CoreProtocolRpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected CoreProtocolRpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.CoreBindReply BindMethod(global::Dfproto.CoreBindRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BindMethod(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.CoreBindReply BindMethod(global::Dfproto.CoreBindRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BindMethod, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.CoreBindReply> BindMethodAsync(global::Dfproto.CoreBindRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BindMethodAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.CoreBindReply> BindMethodAsync(global::Dfproto.CoreBindRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BindMethod, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.EmptyMessage RunCommand(global::Dfproto.CoreRunCommandRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RunCommand(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.EmptyMessage RunCommand(global::Dfproto.CoreRunCommandRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RunCommand, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.EmptyMessage> RunCommandAsync(global::Dfproto.CoreRunCommandRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RunCommandAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.EmptyMessage> RunCommandAsync(global::Dfproto.CoreRunCommandRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RunCommand, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.IntMessage CoreSuspend(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CoreSuspend(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.IntMessage CoreSuspend(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CoreSuspend, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.IntMessage> CoreSuspendAsync(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CoreSuspendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.IntMessage> CoreSuspendAsync(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CoreSuspend, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.IntMessage CoreResume(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CoreResume(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.IntMessage CoreResume(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CoreResume, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.IntMessage> CoreResumeAsync(global::Dfproto.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CoreResumeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.IntMessage> CoreResumeAsync(global::Dfproto.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CoreResume, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.StringListMessage RunLua(global::Dfproto.CoreRunLuaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RunLua(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Dfproto.StringListMessage RunLua(global::Dfproto.CoreRunLuaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RunLua, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.StringListMessage> RunLuaAsync(global::Dfproto.CoreRunLuaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RunLuaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Dfproto.StringListMessage> RunLuaAsync(global::Dfproto.CoreRunLuaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RunLua, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override CoreProtocolRpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CoreProtocolRpcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(CoreProtocolRpcServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_BindMethod, serviceImpl.BindMethod)
          .AddMethod(__Method_RunCommand, serviceImpl.RunCommand)
          .AddMethod(__Method_CoreSuspend, serviceImpl.CoreSuspend)
          .AddMethod(__Method_CoreResume, serviceImpl.CoreResume)
          .AddMethod(__Method_RunLua, serviceImpl.RunLua).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CoreProtocolRpcServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_BindMethod, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.CoreBindRequest, global::Dfproto.CoreBindReply>(serviceImpl.BindMethod));
      serviceBinder.AddMethod(__Method_RunCommand, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.CoreRunCommandRequest, global::Dfproto.EmptyMessage>(serviceImpl.RunCommand));
      serviceBinder.AddMethod(__Method_CoreSuspend, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.EmptyMessage, global::Dfproto.IntMessage>(serviceImpl.CoreSuspend));
      serviceBinder.AddMethod(__Method_CoreResume, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.EmptyMessage, global::Dfproto.IntMessage>(serviceImpl.CoreResume));
      serviceBinder.AddMethod(__Method_RunLua, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dfproto.CoreRunLuaRequest, global::Dfproto.StringListMessage>(serviceImpl.RunLua));
    }

  }
}
#endregion
